### ISSUE TITLE
Second Call Notification Not Being Retreived

### ISSUE THREAD

**Issue by laurenviado** [vcuse/Neurology-iOS-Client#19]
if a call is answered then ended, iPhone won't receive another call until app is rerun. Same problem doesnt persist if first call was declined.

**Comment by deHank** [comment]
- Fixed! This was due to an issue in the code where when disconnected, the client would be removed from the internal list of clients, but not the external facing onlineUsers list. Here is the code: 

![Image](https://github.com/user-attachments/assets/4af5442b-a3f1-412f-8451-c6dae19da53a)

I ended up just putting a boolean so that IOS users will not be removed just for debugging purposes
